### ISSUE TITLE
Podsumowanie wyników

### ISSUE THREAD

**Issue by mrzeszut** [NotASeal23/Projekt#1]
> Porównaj modele, zestaw wyniki oceny dokładności,  napisz wnioski 

 _Originally posted by @mrzeszut in [0055095](https://github.com/NotASeal23/Projekt/commit/00550958a4a11b9c6454dc4c792d4ae1f540522d#r149150699)_

**Comment by NotASeal23** [comment]
Issue solved in recent commit
